import Navbar from '../components/Navbar';
import TopComponent from '../components/TopComponent';
import Footer from '../components/Footer';
import SecondComponent from '../components/SecondComponent';
import ThirdComponent from '../components/ThirdComponent';
import FAQ from '../components/FAQComponent';
import ThreePhotosComponent from '../components/ThreePhotosComponent';
import Contact from '../components/Contact';
import Head from 'next/head';
import MyComponent from '@/components/Mycomponent';

const Home: React.FC = () => {

  const head = () => {
    return (
      <Head>
        <title>Make My Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    )
  }

  return (
    <div className="dotted-bg">
      <Navbar />
      {head()}
      <TopComponent />

      <MyComponent />

      <ThreePhotosComponent />

      <SecondComponent />
      <ThirdComponent />

      <FAQ />
      <Contact />
      <Footer />
    </div>
  );
};

export default Home;
